-- Esquema de la base de Plataforma EA (PostgreSQL).
--
-- Es la fuente de verdad de la estructura: backend/db/conexion.js lo ejecuta al
-- arrancar y PostgreSQL ignora lo que ya existe gracias a IF NOT EXISTS. Para
-- cambiar la forma de una tabla hay que agregar una migración en migrar.js, no
-- editar esto y esperar que se aplique solo.
--
-- Convención de nombres: tablas y columnas en minúscula con guion bajo. El
-- JavaScript usa camelCase, y la traducción entre ambos vive en los
-- repositorios (db/repos/), que es el único sitio que conoce las dos formas.
--
-- Viene de SQLite y conserva a propósito su forma: las fechas siguen siendo
-- TEXT ('YYYY-MM-DD HH:MM:SS' en UTC o ISO 8601, lo mismo que guardaba antes)
-- y los sí/no son INTEGER 0/1, para que ningún repositorio ni el navegador
-- tuvieran que cambiar cómo los leen.

-- Lo que antes era DEFAULT (datetime('now')) de SQLite: mismo formato y en UTC.
CREATE OR REPLACE FUNCTION ahora_txt() RETURNS TEXT
  LANGUAGE sql STABLE
  AS $$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') $$;

-- ---------------------------------------------------------------- personal
-- El padrón de RR.HH. `origen` distingue lo que vino del listado oficial de lo
-- que logística dio de alta a mano: al recargar el padrón, lo manual sobrevive.
CREATE TABLE IF NOT EXISTS personal (
  dni         TEXT PRIMARY KEY,
  nombre      TEXT NOT NULL,
  cargo       TEXT NOT NULL DEFAULT '',
  area        TEXT NOT NULL DEFAULT '',
  origen      TEXT NOT NULL DEFAULT 'padron' CHECK (origen IN ('padron', 'manual')),
  creado_en   TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_personal_nombre ON personal (nombre);

-- ------------------------------------------------------------- solicitudes
-- Un servicio de mensajería. `fuente` distingue lo registrado en la aplicación
-- de lo que se cargó del histórico 2026, que no tiene hora ni vehículo.
CREATE TABLE IF NOT EXISTS solicitudes (
  id              TEXT PRIMARY KEY,
  correlativo     INTEGER NOT NULL,
  creado          TEXT NOT NULL,

  dni             TEXT NOT NULL DEFAULT '',
  nombre          TEXT NOT NULL DEFAULT '',
  cargo           TEXT NOT NULL DEFAULT '',
  area            TEXT NOT NULL DEFAULT '',

  tipo            TEXT NOT NULL CHECK (tipo IN ('Recoger', 'Entregar')),
  servicio        TEXT NOT NULL DEFAULT '',
  motivo          TEXT NOT NULL DEFAULT '',
  origen          TEXT NOT NULL DEFAULT '',
  origen_detalle  TEXT NOT NULL DEFAULT '',
  destino         TEXT NOT NULL DEFAULT '',
  contacto        TEXT NOT NULL DEFAULT '',
  telefono        TEXT NOT NULL DEFAULT '',

  fecha_prog      TEXT NOT NULL DEFAULT '',
  hora_prog       TEXT NOT NULL DEFAULT '',

  vehiculo        TEXT CHECK (vehiculo IS NULL OR vehiculo IN ('Motorizado', 'Carro')),
  costo           DOUBLE PRECISION CHECK (costo IS NULL OR costo >= 0),

  estado          TEXT NOT NULL CHECK (estado IN ('En espera', 'En tránsito', 'Concluido', 'Cancelado')),
  ts_espera       TEXT,
  ts_transito     TEXT,
  ts_concluido    TEXT,

  -- Solo se llenan si `estado` es 'Cancelado'. `motivo_cancelacion` es de las
  -- tres opciones fijas de la pantalla; `_detalle` es el texto libre que solo
  -- pide "Otros". `cancelado_por` guarda quién fue: el usuario de logística
  -- que lo hizo, o "Solicitante" si lo canceló el propio dueño del ticket.
  motivo_cancelacion         TEXT NOT NULL DEFAULT ''
                             CHECK (motivo_cancelacion IN ('', 'Usuario solicitó baja', 'No autorizado', 'Otros')),
  motivo_cancelacion_detalle TEXT NOT NULL DEFAULT '',
  cancelado_por              TEXT NOT NULL DEFAULT '',
  ts_cancelado               TEXT,

  fuente          TEXT NOT NULL DEFAULT 'app' CHECK (fuente IN ('app', 'historico'))
);

-- Los accesos que de verdad se usan: la bandeja filtra por estado, los
-- indicadores agrupan por fecha, el solicitante busca lo suyo por DNI y,
-- desde el ingreso por área, su área pide los últimos 5 servicios por `area`.
CREATE INDEX IF NOT EXISTS idx_solicitudes_estado ON solicitudes (estado);
CREATE INDEX IF NOT EXISTS idx_solicitudes_fecha  ON solicitudes (fecha_prog);
CREATE INDEX IF NOT EXISTS idx_solicitudes_dni    ON solicitudes (dni);
CREATE INDEX IF NOT EXISTS idx_solicitudes_area   ON solicitudes (area);

-- ----------------------------------------------------------------- paradas
-- Destinos adicionales de una solicitud con dos o más rutas en la misma
-- programación. El primer destino sigue viviendo en `solicitudes.destino`
-- -así no cambia nada de lo que ya lee el resto del sistema-; esta tabla solo
-- guarda las paradas de MÁS, en el orden en que se visitan.
CREATE TABLE IF NOT EXISTS paradas (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  TEXT NOT NULL,
  orden      INTEGER NOT NULL,
  destino    TEXT NOT NULL,
  contacto   TEXT NOT NULL DEFAULT '',
  telefono   TEXT NOT NULL DEFAULT '',
  FOREIGN KEY (ticket_id) REFERENCES solicitudes (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_paradas_ticket ON paradas (ticket_id);

-- ---------------------------------------------------------- autorizaciones
-- Pedidos de alta en el padrón de quien intentó entrar sin figurar en él.
-- Antes solo se guardaba el DNI: no alcanzaba para que admin supiera a quién
-- estaba habilitando. Apellidos, nombres y celular son obligatorios para
-- pedirla; email y área quedan a criterio de quien la pide.
CREATE TABLE IF NOT EXISTS autorizaciones (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dni         TEXT NOT NULL,
  apellidos   TEXT NOT NULL DEFAULT '',
  nombres     TEXT NOT NULL DEFAULT '',
  celular     TEXT NOT NULL DEFAULT '',
  email       TEXT NOT NULL DEFAULT '',
  area        TEXT NOT NULL DEFAULT '',
  solicitado  TEXT NOT NULL,
  estado      TEXT NOT NULL DEFAULT 'Pendiente'
              CHECK (estado IN ('Pendiente', 'Aprobada', 'Rechazada'))
);

CREATE INDEX IF NOT EXISTS idx_autorizaciones_estado ON autorizaciones (estado);

-- --------------------------------------------------------- credenciales_area
-- Segundo factor del ingreso del solicitante: el DNI detecta el área (contra
-- `personal`) y esta es la clave de esa área, una sola para todo el mundo que
-- trabaja ahí. No es una tabla de `usuarios` -esas son cuentas personales de
-- logística, con otro ciclo de vida (las crea/desactiva admin una por una) y
-- otro propósito (despachar, no pedir un servicio)-, así que se separan aunque
-- el hash y el patrón de alta sean iguales.
CREATE TABLE IF NOT EXISTS credenciales_area (
  area                TEXT PRIMARY KEY,
  usuario             TEXT NOT NULL UNIQUE,
  clave_hash          TEXT NOT NULL,
  activo              INTEGER NOT NULL DEFAULT 1 CHECK (activo IN (0, 1)),
  debe_cambiar_clave  INTEGER NOT NULL DEFAULT 1 CHECK (debe_cambiar_clave IN (0, 1)),
  creado_por          TEXT NOT NULL DEFAULT '',
  creado_en           TEXT NOT NULL DEFAULT ahora_txt()
);

-- -------------------------------------------------------- pedidos_historico
-- Un área solo ve sus últimos 5 servicios; si necesita uno más viejo o el
-- histórico completo, se lo pide a admin en vez de poder traérselo ella misma.
-- Mismo espíritu que `autorizaciones` (un pedido que admin resuelve a mano),
-- pero es un pedido distinto -ver más, no entrar- y de otra área (no de un
-- DNI), así que es otra tabla en vez de forzar `autorizaciones` a servir para
-- dos cosas.
CREATE TABLE IF NOT EXISTS pedidos_historico (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area        TEXT NOT NULL,
  dni         TEXT NOT NULL DEFAULT '',
  solicitado  TEXT NOT NULL,
  estado      TEXT NOT NULL DEFAULT 'Pendiente'
              CHECK (estado IN ('Pendiente', 'Atendida', 'Rechazada'))
);

CREATE INDEX IF NOT EXISTS idx_pedidos_historico_estado ON pedidos_historico (estado);

-- --------------------------------------------------------------- usuarios
-- Cuentas de logística: quién puede ENTRAR a despachar, ver indicadores o
-- administrar el padrón. No confundir con `personal`, que es quién puede
-- PEDIR un servicio: son universos distintos y del segundo hay cientos.
--
-- rol 'admin'        controles generales, indicadores, payback y padrón.
-- rol 'seguimiento'  bandeja de despacho; para dar de alta a alguien que no
--                    figura en el padrón, pide autorización en vez de poder
--                    agregarlo directo.
CREATE TABLE IF NOT EXISTS usuarios (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario             TEXT NOT NULL UNIQUE,
  clave_hash          TEXT NOT NULL,
  rol                 TEXT NOT NULL CHECK (rol IN ('admin', 'seguimiento')),
  activo              INTEGER NOT NULL DEFAULT 1 CHECK (activo IN (0, 1)),
  debe_cambiar_clave  INTEGER NOT NULL DEFAULT 1 CHECK (debe_cambiar_clave IN (0, 1)),
  creado_por          TEXT NOT NULL DEFAULT '',
  creado_en           TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON usuarios (rol);

-- ----------------------------------------------------------------- adjuntos
-- Metadatos de las guías de entrega. El binario NO vive aquí: multer lo deja en
-- uploads/ y esta tabla guarda con qué nombre quedó. Separarlos mantiene la
-- base pequeña y permite respaldar los archivos por separado.
CREATE TABLE IF NOT EXISTS adjuntos (
  id               TEXT PRIMARY KEY,
  ticket_id        TEXT NOT NULL,
  nombre_original  TEXT NOT NULL,
  archivo          TEXT NOT NULL UNIQUE,
  tipo             TEXT NOT NULL DEFAULT '',
  tamano           INTEGER NOT NULL DEFAULT 0,
  subido_por       TEXT NOT NULL DEFAULT '',
  subido_en        TEXT NOT NULL,
  FOREIGN KEY (ticket_id) REFERENCES solicitudes (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_adjuntos_ticket ON adjuntos (ticket_id);

-- --------------------------------------------------------- eventos_seguridad
-- Auditoría: ingresos, cambios de clave, altas/bajas de usuarios, acciones
-- administrativas y accesos denegados. Nunca se guarda una clave ni un token
-- acá -eso lo garantiza quien llama a `registrar()`, no esta tabla-.
CREATE TABLE IF NOT EXISTS eventos_seguridad (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuando   TEXT NOT NULL DEFAULT ahora_txt(),
  tipo     TEXT NOT NULL,
  usuario  TEXT NOT NULL DEFAULT '',
  ip       TEXT NOT NULL DEFAULT '',
  detalle  TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_eventos_seguridad_cuando ON eventos_seguridad (cuando);
CREATE INDEX IF NOT EXISTS idx_eventos_seguridad_tipo ON eventos_seguridad (tipo);

-- ------------------------------------------------------------------ ajustes
-- Pares clave/valor para lo que no merece una tabla: la clave de logística, la
-- versión del esquema y el testigo de revisión que usa el sondeo del navegador.
CREATE TABLE IF NOT EXISTS ajustes (
  clave  TEXT PRIMARY KEY,
  valor  TEXT NOT NULL
);

-- ================================================ Compras y Logística
-- Tres registros propios del coordinador de logística, además de la
-- mensajería: qué se manda de muestra al exterior, qué hay que comprar y qué
-- servicios se contratan. Ninguno de los tres es visible para "seguimiento":
-- solo admin los administra (ver requiereRol('admin') en las rutas).

-- ------------------------------------------------------------ exportaciones
-- Muestras enviadas a proveedores en el exterior. "Fecha de llegada al
-- proveedor" -no "al cliente"- porque lo que sale de acá son muestras para
-- evaluación, no ventas: el destino final del envío ES el proveedor.
CREATE TABLE IF NOT EXISTS exportaciones (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_envio              TEXT NOT NULL,
  oc                       TEXT NOT NULL DEFAULT '',
  costo_envio              DOUBLE PRECISION CHECK (costo_envio IS NULL OR costo_envio >= 0),
  descripcion              TEXT NOT NULL,
  pais_destino             TEXT NOT NULL,
  fecha_llegada_proveedor  TEXT NOT NULL DEFAULT '',
  motivo                   TEXT NOT NULL DEFAULT '',
  transportista            TEXT NOT NULL DEFAULT '',
  tracking                 TEXT NOT NULL DEFAULT '',
  estado                   TEXT NOT NULL DEFAULT 'En tránsito'
                           CHECK (estado IN ('En tránsito', 'Entregado', 'Devuelto', 'Perdido')),
  responsable              TEXT NOT NULL DEFAULT '',
  notas                    TEXT NOT NULL DEFAULT '',
  creado_por               TEXT NOT NULL DEFAULT '',
  creado_en                TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_exportaciones_estado ON exportaciones (estado);
CREATE INDEX IF NOT EXISTS idx_exportaciones_fecha ON exportaciones (fecha_envio);

-- ------------------------------------------------------- requerimientos_compra
-- Lo que el coordinador de logística tiene que gestionar: materia prima local
-- e importada (resinas, PP, PE de soplado e inyección), repuestos y
-- servicios. `correlativo` es propio -no comparte numeración con `solicitudes`
-- ni con nada más- porque es un universo de compras, no de mensajería.
CREATE TABLE IF NOT EXISTS requerimientos_compra (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correlativo         INTEGER NOT NULL,
  fecha_solicitud     TEXT NOT NULL,
  area_solicitante    TEXT NOT NULL DEFAULT '',
  descripcion         TEXT NOT NULL,
  categoria           TEXT NOT NULL DEFAULT 'Otros'
                      CHECK (categoria IN ('Materia prima local', 'Materia prima importada', 'Repuestos', 'Servicios', 'Otros')),
  cantidad            DOUBLE PRECISION CHECK (cantidad IS NULL OR cantidad >= 0),
  unidad_medida       TEXT NOT NULL DEFAULT '',
  proveedor_sugerido  TEXT NOT NULL DEFAULT '',
  prioridad           TEXT NOT NULL DEFAULT 'Normal' CHECK (prioridad IN ('Urgente', 'Alta', 'Normal', 'Baja')),
  fecha_requerida     TEXT NOT NULL DEFAULT '',
  estado              TEXT NOT NULL DEFAULT 'Pendiente'
                      CHECK (estado IN ('Pendiente', 'Cotizando', 'Aprobado', 'OC emitida', 'Recibido', 'Rechazado', 'Cancelado')),
  numero_oc           TEXT NOT NULL DEFAULT '',
  moneda              TEXT NOT NULL DEFAULT 'PEN' CHECK (moneda IN ('PEN', 'USD')),
  costo_estimado      DOUBLE PRECISION CHECK (costo_estimado IS NULL OR costo_estimado >= 0),
  costo_real          DOUBLE PRECISION CHECK (costo_real IS NULL OR costo_real >= 0),
  observaciones       TEXT NOT NULL DEFAULT '',
  creado_por          TEXT NOT NULL DEFAULT '',
  creado_en           TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_requerimientos_estado ON requerimientos_compra (estado);
CREATE INDEX IF NOT EXISTS idx_requerimientos_categoria ON requerimientos_compra (categoria);

-- --------------------------------------------------------- servicios_logistica
-- Servicios que contrata logística -mantenimiento, transporte especializado,
-- certificaciones, agenciamiento de aduana- y que no son mensajería: por eso
-- es otra tabla y no una fila más de `solicitudes`.
CREATE TABLE IF NOT EXISTS servicios_logistica (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_solicitud  TEXT NOT NULL,
  tipo_servicio    TEXT NOT NULL DEFAULT 'Otro'
                   CHECK (tipo_servicio IN ('Mantenimiento', 'Transporte especializado', 'Certificación', 'Agenciamiento de aduana', 'Consultoría', 'Otro')),
  proveedor        TEXT NOT NULL DEFAULT '',
  descripcion      TEXT NOT NULL,
  costo            DOUBLE PRECISION CHECK (costo IS NULL OR costo >= 0),
  moneda           TEXT NOT NULL DEFAULT 'PEN' CHECK (moneda IN ('PEN', 'USD')),
  estado           TEXT NOT NULL DEFAULT 'Cotizando'
                   CHECK (estado IN ('Cotizando', 'Aprobado', 'En ejecución', 'Concluido', 'Cancelado')),
  fecha_inicio     TEXT NOT NULL DEFAULT '',
  fecha_termino    TEXT NOT NULL DEFAULT '',
  responsable      TEXT NOT NULL DEFAULT '',
  observaciones    TEXT NOT NULL DEFAULT '',
  creado_por       TEXT NOT NULL DEFAULT '',
  creado_en        TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_servicios_logistica_estado ON servicios_logistica (estado);
CREATE INDEX IF NOT EXISTS idx_servicios_logistica_tipo ON servicios_logistica (tipo_servicio);

-- ------------------------------------------------------------ metraje_almacen
-- Alquiler del almacén Los Olivos (CO LOGISTIC PERU): metraje ocupado y costo,
-- por semana ('semanal') o como renta base fija del mes ('mensual', una fila
-- por mes con `mes_label` p.ej. "ENERO"). Se siembra una vez con el histórico
-- de METRAJE ALMACEN LOS OLIVOS.xlsx (data/metrajeAlmacen.js) y de ahí en
-- adelante admin agrega las semanas nuevas a mano -por eso tiene CRUD
-- completo y no es de solo lectura como `ordenes_compra`-.
-- `pendiente_validar` marca filas con datos incompletos en el Excel original
-- (la fila de MARZO sin metraje/precio y la semana 2026-03-02/03-08, que no
-- existía en el archivo): quedan visibles en la tabla pero fuera de los
-- indicadores hasta que alguien las confirme con la factura real.
CREATE TABLE IF NOT EXISTS metraje_almacen (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo              TEXT NOT NULL DEFAULT 'semanal' CHECK (tipo IN ('semanal', 'mensual')),
  fecha_desde       TEXT NOT NULL,
  fecha_hasta       TEXT NOT NULL,
  mes_label         TEXT NOT NULL DEFAULT '',
  precio_m2         DOUBLE PRECISION NOT NULL DEFAULT 0,
  metraje           DOUBLE PRECISION,
  precio_sin_igv    DOUBLE PRECISION,
  total_con_igv     DOUBLE PRECISION,
  factura           TEXT NOT NULL DEFAULT '',
  pendiente_validar INTEGER NOT NULL DEFAULT 0 CHECK (pendiente_validar IN (0, 1)),
  observaciones     TEXT NOT NULL DEFAULT '',
  creado_por        TEXT NOT NULL DEFAULT '',
  creado_en         TEXT NOT NULL DEFAULT ahora_txt(),
  actualizado_en    TEXT NOT NULL DEFAULT ahora_txt(),
  UNIQUE (tipo, fecha_desde, fecha_hasta)
);

CREATE INDEX IF NOT EXISTS idx_metraje_almacen_fecha ON metraje_almacen (fecha_desde);

-- ------------------------------------------------------------- ordenes_compra
-- Registro de compras de SUNAT (data/compras.js, cargado una sola vez por
-- sembrar.js): cada fila es un comprobante ya emitido y contabilizado, no un
-- flujo de aprobación como `requerimientos_compra`. `numero_registro` es la
-- columna "Comprobante" del registro SUNAT y es única por comprobante: sirve
-- de clave natural para no duplicar en una recarga.
CREATE TABLE IF NOT EXISTS ordenes_compra (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_emision     TEXT NOT NULL,
  codigo_sunat      TEXT NOT NULL DEFAULT '',
  tipo_comprobante  TEXT NOT NULL DEFAULT '',
  serie             TEXT NOT NULL DEFAULT '',
  numero_doc        TEXT NOT NULL DEFAULT '',
  numero_registro   TEXT NOT NULL UNIQUE,
  ruc               TEXT NOT NULL DEFAULT '',
  tipo_cambio       DOUBLE PRECISION NOT NULL DEFAULT 0,
  proveedor         TEXT NOT NULL DEFAULT '',
  moneda            TEXT NOT NULL DEFAULT 'PEN' CHECK (moneda IN ('PEN', 'USD')),
  monto_me          DOUBLE PRECISION NOT NULL DEFAULT 0,
  base_gravada      DOUBLE PRECISION NOT NULL DEFAULT 0,
  base_no_gravada   DOUBLE PRECISION NOT NULL DEFAULT 0,
  igv               DOUBLE PRECISION NOT NULL DEFAULT 0,
  igv_no_gravado    DOUBLE PRECISION NOT NULL DEFAULT 0,
  otros             DOUBLE PRECISION NOT NULL DEFAULT 0,
  percepcion        DOUBLE PRECISION NOT NULL DEFAULT 0,
  total             DOUBLE PRECISION NOT NULL DEFAULT 0,
  glosa             TEXT NOT NULL DEFAULT '',
  creado_en         TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_ordenes_compra_proveedor ON ordenes_compra (proveedor);
CREATE INDEX IF NOT EXISTS idx_ordenes_compra_fecha ON ordenes_compra (fecha_emision);

-- ------------------------------------------------------------------ productos
-- Catálogo de productos (SKU) del ERP (data/productos.js, "REPORTE DE
-- PRODUCTOS" de SUNAT/ERP). `codigo` es la clave del ERP: la usa
-- `requerimientos_compra_detalle.codigo_producto` para enlazar cada
-- requerimiento con su producto (ver ese bloque). A diferencia de
-- ordenes_compra, esto SÍ se refresca en cada recarga -el stock cambia todo
-- el tiempo-, así que cargarInicial() hace UPSERT, no ON CONFLICT DO NOTHING.
CREATE TABLE IF NOT EXISTS productos (
  codigo               TEXT PRIMARY KEY,
  codigo_alterno       TEXT NOT NULL DEFAULT '',
  descripcion          TEXT NOT NULL DEFAULT '',
  unidad_medida        TEXT NOT NULL DEFAULT '',
  familia              TEXT NOT NULL DEFAULT '',
  linea                TEXT NOT NULL DEFAULT '',
  marca                TEXT NOT NULL DEFAULT '',
  modelo               TEXT NOT NULL DEFAULT '',
  peso                 DOUBLE PRECISION NOT NULL DEFAULT 0,
  origen               TEXT NOT NULL DEFAULT '',
  tipo_producto         TEXT NOT NULL DEFAULT '',
  estado               TEXT NOT NULL DEFAULT '',
  ubicacion            TEXT NOT NULL DEFAULT '',
  stock_minimo         DOUBLE PRECISION NOT NULL DEFAULT 0,
  lead_time            DOUBLE PRECISION NOT NULL DEFAULT 0,
  stock                DOUBLE PRECISION NOT NULL DEFAULT 0,
  tiene_ficha_tecnica  TEXT NOT NULL DEFAULT 'NO',
  tiene_materia_prima  TEXT NOT NULL DEFAULT 'NO',
  actualizado_en       TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_productos_descripcion ON productos (descripcion);
CREATE INDEX IF NOT EXISTS idx_productos_familia ON productos (familia);
CREATE INDEX IF NOT EXISTS idx_productos_estado ON productos (estado);

-- ------------------------------------------------- requerimientos_compra_detalle
-- Historial de requerimientos de compra ya resuelto por el ERP (data/
-- requerimientosCompraHistorico.js, ".csv/data_rqc.csv"). Es la contraparte
-- de solo lectura de `requerimientos_compra` (la tabla que administra admin
-- desde la app): cada fila es una línea de requerimiento, o una atención
-- parcial de esa línea si se entregó en más de una vez -por eso puede haber
-- varias filas con el mismo (numero_requerimiento, item)-. `clave` es
-- sintética (numero_requerimiento + item + un contador de atención) y sirve
-- para no duplicar en una recarga.
--
-- `codigo_producto` enlaza con `productos.codigo` -no es una FOREIGN KEY
-- porque el ERP a veces trae un código que el catálogo ya dio de baja-, y
-- `proveedor` es el mismo texto de razón social que `ordenes_compra.proveedor`:
-- es la llave con el registro de compras (que no trae número de requerimiento
-- ni código de producto). Con la propia Orden de Compra el enlace es más
-- fino: (ref1_tipo, ref1_serie, ref1_numero) es la misma referencia que
-- (ref_tipo, ref_serie, ref_numero) en `ordenes_compra_detalle` -ver ese
-- bloque más abajo-.
CREATE TABLE IF NOT EXISTS requerimientos_compra_detalle (
  id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave                         TEXT NOT NULL UNIQUE,
  fecha_emision                 TEXT NOT NULL,
  numero_requerimiento_cabecera TEXT NOT NULL DEFAULT '',
  numero_requerimiento          TEXT NOT NULL,
  item                          INTEGER NOT NULL DEFAULT 0,
  codigo_producto               TEXT NOT NULL DEFAULT '',
  nombre_producto               TEXT NOT NULL DEFAULT '',
  unidad_medida                 TEXT NOT NULL DEFAULT '',
  cantidad                      DOUBLE PRECISION NOT NULL DEFAULT 0,
  atendida                      DOUBLE PRECISION NOT NULL DEFAULT 0,
  saldo                         DOUBLE PRECISION NOT NULL DEFAULT 0,
  fecha_entrega_comprometida    TEXT NOT NULL DEFAULT '',
  estado                        TEXT NOT NULL DEFAULT '',
  numero_oc                     TEXT NOT NULL DEFAULT '',
  proveedor                     TEXT NOT NULL DEFAULT '',
  ref1_tipo                     TEXT NOT NULL DEFAULT '',
  ref1_serie                    TEXT NOT NULL DEFAULT '',
  ref1_numero                   TEXT NOT NULL DEFAULT '',
  ref2_tipo                     TEXT NOT NULL DEFAULT '',
  ref2_serie                    TEXT NOT NULL DEFAULT '',
  ref2_numero                   TEXT NOT NULL DEFAULT '',
  fecha_atencion                TEXT NOT NULL DEFAULT '',
  cantidad_atendida             DOUBLE PRECISION NOT NULL DEFAULT 0,
  glosa                         TEXT NOT NULL DEFAULT '',
  creado_en                     TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_rcd_requerimiento ON requerimientos_compra_detalle (numero_requerimiento, item);
CREATE INDEX IF NOT EXISTS idx_rcd_codigo_producto ON requerimientos_compra_detalle (codigo_producto);
CREATE INDEX IF NOT EXISTS idx_rcd_proveedor ON requerimientos_compra_detalle (proveedor);
CREATE INDEX IF NOT EXISTS idx_rcd_estado ON requerimientos_compra_detalle (estado);

-- ------------------------------------------------------- ordenes_compra_detalle
-- Historial de Órdenes de Compra del ERP (data/ordenesCompraDetalle.js,
-- ".csv/OC 2025.csv" y ".csv/OC 2026.csv"). Una OC (numero_oc = doc_serie +
-- '-' + doc_numero) tiene una fila por ítem, así que puede repetirse -por eso
-- `clave` es sintética, igual criterio que requerimientos_compra_detalle-.
--
-- Es un documento DISTINTO del registro de compras SUNAT (ordenes_compra /
-- data/compras.js): la OC es lo que se le da al proveedor, la
-- factura/comprobante es lo que el proveedor entrega después. No comparten
-- número; solo el proveedor (texto y RUC) es exactamente el mismo en ambos.
-- Con requerimientos_compra_detalle el enlace sí es exacto: (ref_tipo,
-- ref_serie, ref_numero) es la misma referencia que (ref1_tipo, ref1_serie,
-- ref1_numero) de ese requerimiento. `codigo_producto` enlaza con
-- productos.codigo, igual que en requerimientos_compra_detalle.
CREATE TABLE IF NOT EXISTS ordenes_compra_detalle (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave                 TEXT NOT NULL UNIQUE,
  codigo_area           TEXT NOT NULL DEFAULT '',
  area                  TEXT NOT NULL DEFAULT '',
  fecha_entrega         TEXT NOT NULL DEFAULT '',
  doc_serie             TEXT NOT NULL DEFAULT '',
  doc_numero            TEXT NOT NULL DEFAULT '',
  numero_oc             TEXT NOT NULL,
  fecha_emision         TEXT NOT NULL DEFAULT '',
  ruc_proveedor         TEXT NOT NULL DEFAULT '',
  proveedor             TEXT NOT NULL DEFAULT '',
  tipo_orden            TEXT NOT NULL DEFAULT '',
  ref_tipo              TEXT NOT NULL DEFAULT '',
  ref_serie             TEXT NOT NULL DEFAULT '',
  ref_numero            TEXT NOT NULL DEFAULT '',
  estado                TEXT NOT NULL DEFAULT '',
  tipo_cambio           DOUBLE PRECISION NOT NULL DEFAULT 0,
  codigo_producto       TEXT NOT NULL DEFAULT '',
  descripcion_producto  TEXT NOT NULL DEFAULT '',
  vencimiento           TEXT NOT NULL DEFAULT '',
  cantidad              DOUBLE PRECISION NOT NULL DEFAULT 0,
  saldo                 DOUBLE PRECISION NOT NULL DEFAULT 0,
  moneda                TEXT NOT NULL DEFAULT 'PEN' CHECK (moneda IN ('PEN', 'USD')),
  costo_unitario        DOUBLE PRECISION NOT NULL DEFAULT 0,
  valor_compra          DOUBLE PRECISION NOT NULL DEFAULT 0,
  proc_descuento        DOUBLE PRECISION NOT NULL DEFAULT 0,
  monto_igv             DOUBLE PRECISION NOT NULL DEFAULT 0,
  monto_neto            DOUBLE PRECISION NOT NULL DEFAULT 0,
  monto_saldo           DOUBLE PRECISION NOT NULL DEFAULT 0,
  valor_compra_mn       DOUBLE PRECISION NOT NULL DEFAULT 0,
  valor_compra_me       DOUBLE PRECISION NOT NULL DEFAULT 0,
  cod_molde             TEXT NOT NULL DEFAULT '',
  nombre_molde          TEXT NOT NULL DEFAULT '',
  glosa_cab_req_compra  TEXT NOT NULL DEFAULT '',
  glosa_det_req_compra  TEXT NOT NULL DEFAULT '',
  incoterm              TEXT NOT NULL DEFAULT '',
  tipo_transporte       TEXT NOT NULL DEFAULT '',
  agente_aduana         TEXT NOT NULL DEFAULT '',
  numero_contrato       TEXT NOT NULL DEFAULT '',
  usuario               TEXT NOT NULL DEFAULT '',
  creado_en             TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_ocd_numero_oc ON ordenes_compra_detalle (numero_oc);
CREATE INDEX IF NOT EXISTS idx_ocd_proveedor ON ordenes_compra_detalle (proveedor);
CREATE INDEX IF NOT EXISTS idx_ocd_codigo_producto ON ordenes_compra_detalle (codigo_producto);
CREATE INDEX IF NOT EXISTS idx_ocd_ref ON ordenes_compra_detalle (ref_tipo, ref_serie, ref_numero);
CREATE INDEX IF NOT EXISTS idx_ocd_estado ON ordenes_compra_detalle (estado);
CREATE INDEX IF NOT EXISTS idx_ocd_fecha ON ordenes_compra_detalle (fecha_emision);
-- Cubre el CTE de rotación ABC de productos (GROUP BY codigo_producto con
-- MAX/filtro por fecha_emision) sin ir a la tabla: la mitad del tiempo.
CREATE INDEX IF NOT EXISTS idx_ocd_producto_fecha ON ordenes_compra_detalle (codigo_producto, fecha_emision);

-- --------------------------------------------------------- materia_prima_stock
-- Stock valorizado de materia prima (data/materiaPrimaStock.js, ".xlsx
-- REPORTE DE STOCK VALORIZADO ACUMULADO", solo el tipo de producto "07
-- MATERIAS PRIMAS"). Es una FOTO del stock a la fecha del reporte -no un
-- histórico como ordenes_compra-: cada recarga BORRA todo y vuelve a
-- insertar (ver backend/db/repos/materiaPrimaStock.js → cargarInicial), no
-- hay ON CONFLICT porque no tiene sentido acumular fotos viejas con la
-- nueva.
--
-- Un mismo `codigo` puede repetirse varias veces -una fila por almacén en el
-- que tiene stock-, así que no hay clave única por producto. `categoria`
-- (SOPLADO/INYECCION/ADITIVOS/MASTERBATCH/FORMULADOS/OTROS) es una
-- clasificación propia derivada de `familia` por palabra clave -el ERP no
-- trae esa columna-, pensada para la navegación Categoría → Línea → Producto
-- del módulo de Materia Prima.
CREATE TABLE IF NOT EXISTS materia_prima_stock (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  almacen_codigo      TEXT NOT NULL DEFAULT '',
  almacen             TEXT NOT NULL DEFAULT '',
  categoria_nivel3    TEXT NOT NULL DEFAULT '',
  familia             TEXT NOT NULL DEFAULT '',
  categoria           TEXT NOT NULL DEFAULT 'OTROS',
  codigo              TEXT NOT NULL DEFAULT '',
  codigo_alterno      TEXT NOT NULL DEFAULT '',
  descripcion         TEXT NOT NULL DEFAULT '',
  unidad_medida       TEXT NOT NULL DEFAULT '',
  ubicacion           TEXT NOT NULL DEFAULT '',
  stock               DOUBLE PRECISION NOT NULL DEFAULT 0,
  costo_promedio_usd  DOUBLE PRECISION NOT NULL DEFAULT 0,
  valorizado_usd      DOUBLE PRECISION NOT NULL DEFAULT 0,
  actualizado_en      TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_mps_categoria ON materia_prima_stock (categoria);
CREATE INDEX IF NOT EXISTS idx_mps_familia ON materia_prima_stock (familia);
CREATE INDEX IF NOT EXISTS idx_mps_codigo ON materia_prima_stock (codigo);
CREATE INDEX IF NOT EXISTS idx_mps_almacen ON materia_prima_stock (almacen);

-- ------------------------------------------------------------- stock_valorizado
-- Stock valorizado COMPLETO del ERP (data/stockValorizado.js): superconjunto
-- de materia_prima_stock -este trae TODOS los tipos de producto (Producto
-- Terminado/APT, Materia Prima/MP, envases, activo fijo, etc.), no solo
-- "07 MATERIAS PRIMAS"-. Sirve para preguntas que cruzan cualquier almacén
-- sin importar el tipo, como "qué SKU y cuánto valorizado tiene el almacén
-- 151" (Control de Almacenes → Plano y Control lo consume vía
-- backend/almacen/src/services/stockAlmacen.js). Misma naturaleza que
-- materia_prima_stock: es una FOTO, se reemplaza entera en cada recarga.
CREATE TABLE IF NOT EXISTS stock_valorizado (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_codigo         TEXT NOT NULL DEFAULT '',
  tipo_producto       TEXT NOT NULL DEFAULT '',
  almacen_codigo      TEXT NOT NULL DEFAULT '',
  almacen             TEXT NOT NULL DEFAULT '',
  categoria_nivel3    TEXT NOT NULL DEFAULT '',
  familia             TEXT NOT NULL DEFAULT '',
  codigo              TEXT NOT NULL DEFAULT '',
  codigo_alterno      TEXT NOT NULL DEFAULT '',
  descripcion         TEXT NOT NULL DEFAULT '',
  unidad_medida       TEXT NOT NULL DEFAULT '',
  ubicacion           TEXT NOT NULL DEFAULT '',
  stock               DOUBLE PRECISION NOT NULL DEFAULT 0,
  costo_promedio_usd  DOUBLE PRECISION NOT NULL DEFAULT 0,
  valorizado_usd      DOUBLE PRECISION NOT NULL DEFAULT 0,
  actualizado_en       TEXT NOT NULL DEFAULT ahora_txt()
);

CREATE INDEX IF NOT EXISTS idx_sv_almacen ON stock_valorizado (almacen_codigo);
CREATE INDEX IF NOT EXISTS idx_sv_codigo ON stock_valorizado (codigo);
CREATE INDEX IF NOT EXISTS idx_sv_tipo ON stock_valorizado (tipo_codigo);
