import { leer, escribir } from './repos/ajustes.js';
import { ejecutarVarias, enTransaccion } from './conexion.js';

/**
 * Migraciones de esquema para una base que YA existe.
 *
 * `esquema.sql` usa `CREATE TABLE IF NOT EXISTS`: le sirve a una base nueva,
 * pero un cambio ahí no le hace nada a una tabla que ya existe. Cada cambio de
 * forma posterior va como un paso acá, que se salta solo si ya se aplicó
 * comprobando `esquema_version` en `ajustes`.
 *
 * Historia: las versiones 1 a 3 fueron de la época de SQLite (el estado
 * 'Cancelado' en `solicitudes` y los datos de contacto en `autorizaciones`).
 * La base PostgreSQL nació ya con esa forma -esquema.sql es la versión 3
 * completa-, así que arranca directamente en 3 y los pasos nuevos empiezan en
 * 4. A diferencia de SQLite, PostgreSQL sí deja cambiar un CHECK con
 * `ALTER TABLE … DROP/ADD CONSTRAINT` y todo el DDL entra en una transacción,
 * así que ya no hace falta recrear tablas para migrar.
 *
 * `migrar()` se corre siempre al arrancar (ver conexion.js).
 */
const VERSION_ACTUAL = 10;
/** La versión que deja esquema.sql por sí solo, en una base nueva. */
const VERSION_ESQUEMA_SQL = 3;

/**
 * 4: formulario de solicitud con mapa y tipo de destino.
 *   - solicitudes: coordenadas del punto elegido en el mapa (origen "Otros"
 *     y destino) y si el destino es Cliente o Proveedor.
 *   - destinos_registrados: cada dirección nueva que un solicitante clasificó.
 *     La siguiente vez ya es conocida y no se vuelve a preguntar.
 * IF NOT EXISTS en todo: corre igual sobre una base nueva (esquema.sql sigue
 * en la versión 3) que sobre una existente, y repetirlo no rompe nada.
 */
/**
 * 5: modalidad del servicio (Envíos / Transporte / Cargo) y cuánto se usa
 * cada destino registrado -para ofrecer primero los que más se repiten y
 * canalizar las redacciones nuevas hacia ellos-.
 */
/**
 * 6: vehículos de carga. Con la modalidad Cargo / Flete, logística asigna
 * también furgón o camión, no solo moto o carro.
 */
/**
 * 7: registro de muestras de materia prima que llegan al almacén (pestaña
 * "Muestras" de Materia Prima). Es un registro propio de logística -no viene
 * del ERP-, con su evaluación: así se sabe cuánto se invirtió en muestras,
 * de quién y cuáles terminaron aprobadas.
 */
/**
 * 8: códigos de materia prima.
 *   - productos.fecha_registro: fecha de alta del código en el ERP (viene de
 *     Mongo) y productos_alta: cuándo vio la plataforma cada código por
 *     primera vez -respaldo si el ERP no trae la fecha-. Con eso Materia
 *     Prima y Homologados muestran los códigos nuevos.
 *   - muestras_mp: el código interno se detecta solo por la descripción
 *     (codigo_auto = 1) y el estado "Aprobada c/restricción", que pasa tal
 *     cual a Homologados.
 */
/**
 * 9: Radar de Importaciones (antes el repo RADAR-EA, con su propia base).
 * Sus tablas viven ahora en el esquema "radar" de ESTA base: el ETL en
 * Python (backend/radar/etl) escribe ahí con search_path=radar y la
 * plataforma lee de ahí (backend/radar/consultas.js). Es el mismo modelo que
 * tenían sus migraciones Alembic 0001-0003, que dejan de existir: el esquema
 * lo versiona solo este archivo, para que no haya dos dueños del DDL.
 */
/**
 * 10: importaciones y planeación de materia prima, ambas copiadas del MongoDB
 * del bot (backend/mongo/sincronizar.js) y reemplazadas enteras en cada copia.
 *   - importaciones: una fila por importación del bot (OC o solicitud), ya
 *     normalizada en `datos` (JSONB): son ~150 filas con 60 campos que el bot
 *     va agregando, así que no vale la pena una columna por campo.
 *   - importaciones_eventos: hitos del rastreo automático con la naviera o el
 *     courier (zarpe, arribo, entrega…).
 *   - mp_planeacion: consumo promedio, lead time, pedidos en camino y compra
 *     sugerida por código de materia prima -la base de la clasificación ABC y
 *     del punto de reorden (shared/abc.js)-.
 */
async function migrarA10() {
  await enTransaccion(() => ejecutarVarias(`
    CREATE TABLE IF NOT EXISTS importaciones (
      id         TEXT PRIMARY KEY,
      oc_numero  TEXT NOT NULL DEFAULT '',
      datos      JSONB NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_importaciones_oc ON importaciones (oc_numero);
    CREATE TABLE IF NOT EXISTS importaciones_eventos (
      id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      importacion_id  TEXT NOT NULL DEFAULT '',
      oc_numero       TEXT NOT NULL DEFAULT '',
      fecha           TEXT NOT NULL DEFAULT '',
      hito            TEXT NOT NULL DEFAULT '',
      descripcion     TEXT NOT NULL DEFAULT '',
      transportista   TEXT NOT NULL DEFAULT '',
      referencia      TEXT NOT NULL DEFAULT '',
      ubicacion       TEXT NOT NULL DEFAULT ''
    );
    CREATE INDEX IF NOT EXISTS idx_importaciones_eventos_imp ON importaciones_eventos (importacion_id);
    CREATE TABLE IF NOT EXISTS mp_planeacion (
      codigo                TEXT PRIMARY KEY,
      descripcion           TEXT NOT NULL DEFAULT '',
      tipo                  TEXT NOT NULL DEFAULT '',
      linea                 TEXT NOT NULL DEFAULT '',
      unidad_medida         TEXT NOT NULL DEFAULT '',
      stock                 DOUBLE PRECISION NOT NULL DEFAULT 0,
      consumo_mes           DOUBLE PRECISION NOT NULL DEFAULT 0,
      consumo_p95           DOUBLE PRECISION NOT NULL DEFAULT 0,
      costo_usd             DOUBLE PRECISION NOT NULL DEFAULT 0,
      lead_time_meses       DOUBLE PRECISION NOT NULL DEFAULT 0,
      seguridad_pct         DOUBLE PRECISION NOT NULL DEFAULT 0,
      en_camino             DOUBLE PRECISION NOT NULL DEFAULT 0,
      compra_sugerida       DOUBLE PRECISION NOT NULL DEFAULT 0,
      compra_sugerida_usd   DOUBLE PRECISION NOT NULL DEFAULT 0,
      estado_demanda        TEXT NOT NULL DEFAULT '',
      proveedor_ultima      TEXT NOT NULL DEFAULT '',
      fecha_ultima_compra   TEXT NOT NULL DEFAULT '',
      ultimo_costo_usd      DOUBLE PRECISION NOT NULL DEFAULT 0
    );
  `));
}

async function migrarA9() {
  await enTransaccion(() => ejecutarVarias(`
    CREATE SCHEMA IF NOT EXISTS radar;
    CREATE TABLE IF NOT EXISTS radar.artifacts (
      id VARCHAR(64) PRIMARY KEY,
      source VARCHAR(60) NOT NULL,
      url TEXT NOT NULL,
      path TEXT NOT NULL,
      downloaded_at TIMESTAMPTZ NOT NULL,
      period JSON NOT NULL,
      bytes INTEGER NOT NULL
    );
    CREATE TABLE IF NOT EXISTS radar.runs (
      id VARCHAR(36) PRIMARY KEY,
      kind VARCHAR(40) NOT NULL,
      parameters JSON NOT NULL,
      status VARCHAR(20) NOT NULL,
      started_at TIMESTAMPTZ NOT NULL,
      finished_at TIMESTAMPTZ,
      result JSON NOT NULL,
      error TEXT
    );
    CREATE TABLE IF NOT EXISTS radar.operations (
      id SERIAL PRIMARY KEY,
      country VARCHAR(2) NOT NULL,
      regime VARCHAR(2) NOT NULL,
      customs VARCHAR(3) NOT NULL,
      year INTEGER NOT NULL,
      declaration VARCHAR(8) NOT NULL,
      series INTEGER NOT NULL,
      numbered_on DATE NOT NULL,
      importer_ruc VARCHAR(11),
      importer TEXT,
      supplier TEXT,
      supplier_status VARCHAR(30) NOT NULL,
      origin VARCHAR(3),
      acquisition_country VARCHAR(3),
      hs_code VARCHAR(10) NOT NULL,
      description TEXT NOT NULL,
      material VARCHAR(30) NOT NULL,
      classification_reason TEXT NOT NULL,
      needs_review BOOLEAN NOT NULL,
      classification_locked BOOLEAN NOT NULL,
      currency VARCHAR(3) NOT NULL,
      quantity NUMERIC(22, 6),
      unit VARCHAR(20),
      net_kg NUMERIC(22, 6),
      kg_method TEXT,
      fob_usd NUMERIC(22, 6),
      freight_usd NUMERIC(22, 6),
      insurance_usd NUMERIC(22, 6),
      cif_usd NUMERIC(22, 6),
      usd_kg NUMERIC(22, 8),
      search_text TEXT NOT NULL,
      quality_flags JSON NOT NULL,
      raw JSON NOT NULL,
      record_hash VARCHAR(64) NOT NULL,
      source_priority INTEGER NOT NULL,
      source_modified_on DATE,
      source_url TEXT NOT NULL,
      artifact_id VARCHAR(64) NOT NULL REFERENCES radar.artifacts (id),
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL,
      plastics_scope BOOLEAN NOT NULL DEFAULT true,
      brand TEXT, grade TEXT, grade_key VARCHAR(40), application VARCHAR(40), applications TEXT,
      melt_index NUMERIC(12, 4), density NUMERIC(8, 4), product_name TEXT, grade_text TEXT, grade_info JSON,
      CONSTRAINT uq_operation UNIQUE (country, regime, customs, year, declaration, series)
    );
    CREATE TABLE IF NOT EXISTS radar.alerts (
      id SERIAL PRIMARY KEY,
      fingerprint VARCHAR(100) NOT NULL UNIQUE,
      kind VARCHAR(30) NOT NULL,
      operation_id INTEGER NOT NULL REFERENCES radar.operations (id),
      title TEXT NOT NULL,
      detail JSON NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      read BOOLEAN NOT NULL
    );
    CREATE TABLE IF NOT EXISTS radar.reviews (
      id SERIAL PRIMARY KEY,
      operation_id INTEGER NOT NULL REFERENCES radar.operations (id),
      previous_material VARCHAR(30) NOT NULL,
      material VARCHAR(30) NOT NULL,
      note TEXT NOT NULL,
      actor VARCHAR(100) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );
    CREATE TABLE IF NOT EXISTS radar.revisions (
      id SERIAL PRIMARY KEY,
      operation_id INTEGER NOT NULL REFERENCES radar.operations (id),
      artifact_id VARCHAR(64) NOT NULL REFERENCES radar.artifacts (id),
      record_hash VARCHAR(64) NOT NULL,
      raw JSON NOT NULL,
      observed_at TIMESTAMPTZ NOT NULL,
      CONSTRAINT uq_revision UNIQUE (operation_id, record_hash)
    );
    CREATE INDEX IF NOT EXISTS ix_operations_hs_code ON radar.operations (hs_code);
    CREATE INDEX IF NOT EXISTS ix_operations_importer_date ON radar.operations (importer_ruc, numbered_on);
    CREATE INDEX IF NOT EXISTS ix_operations_importer_ruc ON radar.operations (importer_ruc);
    CREATE INDEX IF NOT EXISTS ix_operations_material ON radar.operations (material);
    CREATE INDEX IF NOT EXISTS ix_operations_numbered_on ON radar.operations (numbered_on);
    CREATE INDEX IF NOT EXISTS ix_operations_origin ON radar.operations (origin);
    CREATE INDEX IF NOT EXISTS ix_operations_plastics_scope ON radar.operations (plastics_scope);
    CREATE INDEX IF NOT EXISTS ix_operations_grade_key ON radar.operations (grade_key);
    CREATE INDEX IF NOT EXISTS ix_operations_application ON radar.operations (application);
    CREATE INDEX IF NOT EXISTS ix_reviews_operation_id ON radar.reviews (operation_id);
    CREATE INDEX IF NOT EXISTS ix_revisions_operation_id ON radar.revisions (operation_id);
  `));
}

async function migrarA8() {
  await enTransaccion(() => ejecutarVarias(`
    ALTER TABLE productos ADD COLUMN IF NOT EXISTS fecha_registro TEXT NOT NULL DEFAULT '';
    CREATE TABLE IF NOT EXISTS productos_alta (
      codigo    TEXT PRIMARY KEY,
      visto_en  TEXT NOT NULL DEFAULT ''
    );
    ALTER TABLE muestras_mp ADD COLUMN IF NOT EXISTS codigo_auto INTEGER NOT NULL DEFAULT 0;
    ALTER TABLE muestras_mp DROP CONSTRAINT IF EXISTS muestras_mp_estado_check;
    ALTER TABLE muestras_mp ADD CONSTRAINT muestras_mp_estado_check
      CHECK (estado IN ('Recibida', 'En evaluación', 'Aprobada', 'Aprobada c/restricción', 'Rechazada'));
    CREATE INDEX IF NOT EXISTS idx_muestras_codigo ON muestras_mp (codigo_producto);
  `));
}

async function migrarA7() {
  await enTransaccion(() => ejecutarVarias(`
    CREATE TABLE IF NOT EXISTS muestras_mp (
      id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      fecha_llegada    TEXT NOT NULL,
      ruc_proveedor    TEXT NOT NULL DEFAULT '',
      proveedor        TEXT NOT NULL DEFAULT '',
      descripcion      TEXT NOT NULL,
      familia          TEXT NOT NULL DEFAULT '',
      codigo_producto  TEXT NOT NULL DEFAULT '',
      cantidad_kg      DOUBLE PRECISION NOT NULL CHECK (cantidad_kg >= 0),
      precio_kg        DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (precio_kg >= 0),
      moneda           TEXT NOT NULL DEFAULT 'USD' CHECK (moneda IN ('USD', 'PEN')),
      estado           TEXT NOT NULL DEFAULT 'Recibida'
                       CHECK (estado IN ('Recibida', 'En evaluación', 'Aprobada', 'Rechazada')),
      observaciones    TEXT NOT NULL DEFAULT '',
      creado_por       TEXT NOT NULL DEFAULT '',
      creado_en        TEXT NOT NULL DEFAULT ahora_txt(),
      actualizado_en   TEXT NOT NULL DEFAULT ahora_txt()
    );
    CREATE INDEX IF NOT EXISTS idx_muestras_fecha ON muestras_mp (fecha_llegada);
    CREATE INDEX IF NOT EXISTS idx_muestras_ruc ON muestras_mp (ruc_proveedor);
  `));
}

async function migrarA6() {
  await enTransaccion(() => ejecutarVarias(`
    ALTER TABLE solicitudes DROP CONSTRAINT IF EXISTS solicitudes_vehiculo_check;
    ALTER TABLE solicitudes ADD CONSTRAINT solicitudes_vehiculo_check
      CHECK (vehiculo IS NULL OR vehiculo IN ('Motorizado', 'Carro', 'Furgón', 'Camión'));
  `));
}

async function migrarA5() {
  await enTransaccion(() => ejecutarVarias(`
    ALTER TABLE solicitudes ADD COLUMN IF NOT EXISTS modalidad TEXT NOT NULL DEFAULT '';
    ALTER TABLE solicitudes DROP CONSTRAINT IF EXISTS solicitudes_modalidad_check;
    ALTER TABLE solicitudes ADD CONSTRAINT solicitudes_modalidad_check CHECK (modalidad IN ('', 'Envíos', 'Transporte', 'Cargo'));
    ALTER TABLE destinos_registrados ADD COLUMN IF NOT EXISTS usos INTEGER NOT NULL DEFAULT 1;
    ALTER TABLE destinos_registrados ADD COLUMN IF NOT EXISTS ultimo_uso TEXT NOT NULL DEFAULT ahora_txt();
  `));
}

async function migrarA4() {
  await enTransaccion(() => ejecutarVarias(`
    ALTER TABLE solicitudes ADD COLUMN IF NOT EXISTS origen_lat DOUBLE PRECISION;
    ALTER TABLE solicitudes ADD COLUMN IF NOT EXISTS origen_lng DOUBLE PRECISION;
    ALTER TABLE solicitudes ADD COLUMN IF NOT EXISTS destino_lat DOUBLE PRECISION;
    ALTER TABLE solicitudes ADD COLUMN IF NOT EXISTS destino_lng DOUBLE PRECISION;
    ALTER TABLE solicitudes ADD COLUMN IF NOT EXISTS destino_tipo TEXT NOT NULL DEFAULT '';
    ALTER TABLE solicitudes DROP CONSTRAINT IF EXISTS solicitudes_destino_tipo_check;
    ALTER TABLE solicitudes ADD CONSTRAINT solicitudes_destino_tipo_check CHECK (destino_tipo IN ('', 'Cliente', 'Proveedor'));
    CREATE TABLE IF NOT EXISTS destinos_registrados (
      clave       TEXT PRIMARY KEY,
      direccion   TEXT NOT NULL,
      tipo        TEXT NOT NULL CHECK (tipo IN ('Cliente', 'Proveedor')),
      lat         DOUBLE PRECISION,
      lng         DOUBLE PRECISION,
      area        TEXT NOT NULL DEFAULT '',
      creado_por  TEXT NOT NULL DEFAULT '',
      creado_en   TEXT NOT NULL DEFAULT ahora_txt()
    );
  `));
}

export async function migrar() {
  // Una base recién creada no tiene la clave todavía: arranca en la versión
  // de esquema.sql (3), no en la actual, para que corran los pasos nuevos.
  const desde = Number(await leer('esquema_version', String(VERSION_ESQUEMA_SQL)));
  if (desde < 4) await migrarA4();
  if (desde < 5) await migrarA5();
  if (desde < 6) await migrarA6();
  if (desde < 7) await migrarA7();
  if (desde < 8) await migrarA8();
  if (desde < 9) await migrarA9();
  if (desde < 10) await migrarA10();
  if (desde < VERSION_ACTUAL || !(await leer('esquema_version'))) {
    await escribir('esquema_version', String(VERSION_ACTUAL));
  }
}
